"""Compile an editor DAG to a bounded C++ recipe, regenerated by generate_assets.py."""
import json
import copy
import hashlib
import re
from pathlib import Path
from art_profiles import load_catalog as load_art_catalog, profile_key, profiles_for_entries, validate_profile
from shop_catalog import TOWN_COUNT, load_catalog as load_shop_catalog, normalize_profile as normalize_shop_profile, resolve_inventory

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = json.loads((ROOT / 'tools/map_editor/schema.json').read_text())
OPS = {op['id']: (i, op) for i, op in enumerate(SCHEMA['operations'])}
LUT_MAX_POINTS = 255
PARAM_WORDS = 64
MAX_NODES = 64
LUT_COLORS = ('#759bc7','#d6a466','#83ad79','#bd7f9f','#9a8ac7','#63aaa2','#c58a67','#a4a766')
LIBRARY_PATH = ROOT / 'maps/map-library.json'
MAP_ID = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
PLACEMENT_ID = re.compile(r'^[a-z0-9]+(?:_[a-z0-9]+)*$')
MAP_NAME = re.compile(r'^[A-Za-z0-9 .+\-/]+$')
DEFAULT_SPAWN_PROFILES = [{'id': 0, 'name': 'Raider', 'color': '#ef6c5b', 'enemy': 'raider',
                           'respawnSeconds': 30, 'scrapChance': 70, 'scrapMin': 1, 'scrapMax': 3,
                           'energyChance': 25, 'energyMin': 8, 'energyMax': 16}]
ENEMIES = {'scout': 0, 'raider': 1, 'heavy': 2}


def default_lut_color(value):
    return LUT_COLORS[((value * 37) ^ (value >> 2)) % len(LUT_COLORS)]


def integer(value, low, high, name):
    if type(value) is not int or not low <= value <= high:
        raise ValueError(f'{name} must be an integer between {low} and {high}')
    return value


def spawn_profiles(recipe):
    profiles = recipe.get('spawnProfiles', DEFAULT_SPAWN_PROFILES)
    if not isinstance(profiles, list) or not 1 <= len(profiles) <= 8:
        raise ValueError('Use between 1 and 8 spawn profiles')
    ids = set()
    for profile in profiles:
        if not isinstance(profile, dict):
            raise ValueError('Spawn profiles must be objects')
        identity = integer(profile.get('id'), 0, 255, 'Spawn profile ID')
        if identity in ids:
            raise ValueError('Spawn profile IDs must be unique')
        ids.add(identity)
        name = profile.get('name')
        if not isinstance(name, str) or not 1 <= len(name) <= 18 or not MAP_NAME.fullmatch(name):
            raise ValueError('Spawn profile names must use 1-18 title-safe characters')
        if profile.get('enemy') not in ENEMIES:
            raise ValueError('Unknown enemy in spawn profile')
        integer(profile.get('respawnSeconds'), 1, 600, 'Respawn seconds')
        integer(profile.get('scrapChance'), 0, 100, 'Scrap chance')
        minimum = integer(profile.get('scrapMin'), 0, 15, 'Minimum scrap')
        integer(profile.get('scrapMax'), minimum, 15, 'Maximum scrap')
        profile.setdefault('energyChance', 25)
        profile.setdefault('energyMin', 8)
        profile.setdefault('energyMax', 16)
        integer(profile.get('energyChance'), 0, 100, 'Energy chance')
        energy_minimum = integer(profile.get('energyMin'), 0, 100, 'Minimum energy')
        integer(profile.get('energyMax'), energy_minimum, 100, 'Maximum energy')
    return profiles


def placements(recipe, map_id='map'):
    portals = recipe.get('portals', [])
    player_spawns = recipe.get('playerSpawns', [])
    if not isinstance(portals, list) or len(portals) > 8:
        raise ValueError(f'Map {map_id} must contain at most 8 portals')
    if not isinstance(player_spawns, list) or len(player_spawns) > 16:
        raise ValueError(f'Map {map_id} must contain at most 16 player spawns')
    for label, items, fields in (
        ('portal', portals, (('x',0,8191),('y',0,8191),('width',16,512),('height',16,512))),
        ('player spawn', player_spawns, (('x',0,8191),('y',0,8191),('heading',0,359)))):
        identities = set()
        for item in items:
            identity = item.get('id') if isinstance(item, dict) else None
            if not isinstance(identity, str) or len(identity) > 24 or not PLACEMENT_ID.fullmatch(identity):
                raise ValueError(f'Map {map_id} has an invalid {label} ID')
            if identity in identities:
                raise ValueError(f'Map {map_id} has duplicate {label} {identity}')
            identities.add(identity)
            for name, low, high in fields:
                integer(item.get(name), low, high, f'Map {map_id} {label} {identity} {name}')
    return portals, player_spawns


def upgrade_node(node):
    if node.get('type') == 'material_fill':
        node['type'] = 'field_fill'
        if node.get('label') == 'Fill material':
            node['label'] = 'Constant field'
    if node.get('type') == 'material_paint':
        node['type'] = 'field_paint'
        if node.get('label') == 'Paint material':
            node['label'] = 'Paint field value'
    if node.get('type') == 'material_bands':
        params = node.get('p')
        if isinstance(params, list) and len(params) == 7:
            boundaries, values = params[:3], params[3:]
            initial, points = values[0], []
            for position, output in zip(boundaries, values[1:]):
                if position == 0:
                    initial = output
                elif points and points[-1][0] == position:
                    points[-1][1] = output
                else:
                    points.append([position, output])
            node['p'] = [len(points), initial, *(value for point in points for value in point)]
        node['type'] = 'field_lut'
        if node.get('label') == 'Field to materials':
            node['label'] = 'Stepped LUT'
    if node.get('type') == 'field_lut':
        params = node.get('p')
        if isinstance(params, list) and params and type(params[0]) is int and 0 <= params[0] <= LUT_MAX_POINTS:
            count = params[0]
            if len(params) >= 2 + count * 2:
                node['p'] = params = params[:2 + count * 2]
            outputs = [params[1] if len(params) > 1 else 0]
            outputs.extend(params[3 + index * 2] if len(params) > 3 + index * 2 else 0 for index in range(count))
            colors = node.get('colors') if isinstance(node.get('colors'), list) else []
            node['colors'] = [colors[index] if index < len(colors) and isinstance(colors[index], str) and
                              len(colors[index]) == 7 and colors[index][0] == '#' else default_lut_color(output)
                              for index, output in enumerate(outputs)]


def compiled_parameters(node):
    params = node['p']
    if node['type'] != 'field_lut':
        return params
    points = sorted((params[2 + index * 2], params[3 + index * 2]) for index in range(params[0]))
    lookup, output, point = [], params[1], 0
    for input_value in range(256):
        while point < len(points) and points[point][0] <= input_value:
            output = points[point][1]
            point += 1
        lookup.append(output)
    result = []
    for offset in range(0, 256, 4):
        word = sum(lookup[offset + byte] << (byte * 8) for byte in range(4))
        result.append(word - (1 << 32) if word >= (1 << 31) else word)
    return result


def compile_recipe(recipe, target=None):
    if recipe.get('version') not in (1, 2, 3, 4, 5, 6, 7):
        raise ValueError('Unsupported recipe version')
    integer(recipe.get('seed'), 0, 0xffffffff, 'Seed')
    spawn_profiles(recipe)
    nodes = recipe.get('nodes', [])
    if not 1 <= len(nodes) <= MAX_NODES:
        raise ValueError(f'Recipe must contain 1 to {MAX_NODES} nodes')
    lookup = {}
    for node in nodes:
        upgrade_node(node)
        key = integer(node.get('id'), 1, 0x7fffffff, 'Node ID')
        if key in lookup or node.get('type') not in OPS:
            raise ValueError('Duplicate node ID or unknown operation')
        _, spec = OPS[node['type']]
        integer(node.get('stream', 0), 0, 0xffffffff, 'Random stream')
        params = node.get('p', [])
        if node['type'] == 'roads' and len(params) == 3:
            integer(params[0],8,256,'Minimum road width')
            integer(params[2],params[0],256,'Maximum road width')
            params=[params[0] if params[0]==params[2] else (params[0]+params[2]+8)//16*8,params[1]]
            node['p']=params
        if node['type'] == 'field_lut':
            if not params or type(params[0]) is not int or len(params) != 2 + params[0] * 2:
                raise ValueError(f'Invalid LUT data on node {key}')
            integer(params[0], 0, LUT_MAX_POINTS, 'Point count')
            integer(params[1], 0, 255, 'Initial output')
            for index in range(params[0]):
                integer(params[2 + index * 2], 1, 255, f'Point {index + 1} position')
                integer(params[3 + index * 2], 0, 255, f'Point {index + 1} output')
            positions = [params[2 + index * 2] for index in range(params[0])]
            if len(set(positions)) != len(positions):
                raise ValueError('Stepped LUT points need unique positions')
        else:
            if len(params) != len(spec['parameters']):
                raise ValueError(f'Wrong parameter count on node {key}')
            for value, param in zip(params, spec['parameters']):
                integer(value, param[2], param[3], param[0])
                if len(param) > 4 and param[4] == 'neighbours' and value not in (4, 8):
                    raise ValueError('Neighbourhood must be 4 or 8')
        lookup[key] = node
    if recipe['version'] == 2 and lookup.get(recipe.get('materialOutput'), {}).get('type') != 'materials':
        raise ValueError('Choose a Ground materials output')
    if recipe['version'] == 1 and recipe.get('materialOutput') is not None:
        raise ValueError('Material outputs require recipe version 2')
    for key,kind in [('materialOutput','materials'),('spawnOutput','spawns'),('decorationOutput','decoration')]:
        if recipe.get(key) is not None and lookup.get(recipe[key],{}).get('type')!=kind:
            raise ValueError('Invalid '+key)
    if recipe['version']<3 and any(recipe.get(k) is not None for k in ('spawnOutput','decorationOutput')):
        raise ValueError('Placement outputs require recipe version 3')
    order, visiting, done = [], set(), set()

    def visit(key):
        if type(key) is not int or key not in lookup:
            raise ValueError('Missing input or output node')
        if key in visiting:
            raise ValueError('Graph contains a cycle')
        if key in done:
            return
        visiting.add(key)
        node = lookup[key]
        spec = OPS[node['type']][1]
        inputs = node.get('inputs', {})
        if set(inputs) - set(spec['inputs']):
            raise ValueError('Unknown input port')
        for port, expected in spec['inputs'].items():
            source = inputs.get(port)
            if source is None and expected.endswith('?'):
                continue
            visit(source)
            if OPS[lookup[source]['type']][1]['kind'] != expected.rstrip('?'):
                raise ValueError(f'Wrong input type on node {key}: {port}')
        visiting.remove(key)
        done.add(key)
        order.append(key)

    # Validate disconnected draft branches too, but only export the output's ancestors.
    for key in lookup:
        visit(key)
    order.clear()
    done.clear()
    visit(recipe.get('output') if target is None else target)
    if target is None and lookup[recipe['output']]['type'] not in ('world', 'roads'):
        raise ValueError('ROM output must be a Playable world node')
    indices = {key: i for i, key in enumerate(order)}
    program = []
    for key in order:
        node = lookup[key]
        inputs = node.get('inputs', {})
        params = compiled_parameters(node)
        program.append([OPS[node['type']][0], *[indices.get(inputs.get(p), -1) for p in ('a', 'b', 'mask')],
                        node.get('stream', 0), *params, *([0] * (PARAM_WORDS-len(params)))])
    # Same conservative liveness schedule as the portable executor.
    last = list(range(len(program)))
    for i, node in enumerate(program):
        for source in node[1:4]:
            if source >= 0:
                last[source] = i
    peak = max(sum(end >= i for end in last[:i]) + 1 for i in range(len(program)))
    if peak > 6:
        raise ValueError(f'Recipe needs {peak} live buffers; the GBA limit is 6')
    return program


def reconcile_world(library, enabled, portals, player_spawns):
    """Make the saved world graph match the current enabled map interfaces."""
    enabled_ids = {entry['id'] for entry in enabled}
    existing = library.get('world')
    if not isinstance(existing, dict) or existing.get('version') != 2:
        existing = {}

    positioned = {}
    for node in existing.get('nodes', []) if isinstance(existing.get('nodes'), list) else []:
        if isinstance(node, dict) and node.get('map') in enabled_ids and node['map'] not in positioned:
            positioned[node['map']] = node
    nodes = []
    for index, entry in enumerate(enabled):
        previous = positioned.get(entry['id'])
        nodes.append({'map': entry['id'],
                      'x': previous.get('x') if previous else 80 + (index % 4) * 250,
                      'y': previous.get('y') if previous else 70 + (index // 4) * 210})

    connections, used = [], set()
    existing_connections = existing.get('connections')
    if isinstance(existing_connections, list):
        for link in existing_connections:
            if not isinstance(link, dict):
                continue
            source, destination = link.get('from'), link.get('to')
            if not isinstance(source, dict) or not isinstance(destination, dict):
                continue
            source_map, destination_map = source.get('map'), destination.get('map')
            source_portal, destination_spawn = source.get('portal'), destination.get('spawn')
            key = (source_map, source_portal)
            if source_map not in enabled_ids or source_portal not in portals.get(source_map, {}) or \
               destination_map not in enabled_ids or destination_spawn not in player_spawns.get(destination_map, {}) or \
               key in used:
                continue
            used.add(key)
            connections.append({'from': {'map': source_map, 'portal': source_portal},
                                'to': {'map': destination_map, 'spawn': destination_spawn}})
            if len(connections) == 256:
                break

    start = existing.get('start') if isinstance(existing.get('start'), dict) else {}
    start_map = start.get('map') if start.get('map') in enabled_ids else enabled[0]['id']
    start_spawn = start.get('spawn')
    if start_spawn not in player_spawns[start_map]:
        start_spawn = next(iter(player_spawns[start_map]))
    library['world'] = {'version': 2, 'start': {'map': start_map, 'spawn': start_spawn},
                        'nodes': nodes, 'connections': connections}


def validate_library(library, compile_maps=True):
    """Validate the shared editor/ROM catalog and return its enabled entries.

    Draft recipes intentionally receive only bounded structural checks. They
    may be incomplete while the user is building a graph. Enabled recipes must
    compile completely because they are emitted into the connected ROM world.
    """
    if not isinstance(library, dict) or library.get('libraryVersion') != 1:
        raise ValueError('Unsupported map library format')
    entries = library.get('maps')
    if not isinstance(entries, list) or not 1 <= len(entries) <= 64:
        raise ValueError('Map library must contain between 1 and 64 maps')
    ids, enabled = set(), []
    declared_ids = {entry.get('id') for entry in entries if isinstance(entry, dict) and isinstance(entry.get('id'), str)}
    shop_catalog = load_shop_catalog(map_ids=declared_ids)
    art_catalog = load_art_catalog()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise ValueError(f'Map {index + 1} must be an object')
        map_id = entry.get('id')
        if not isinstance(map_id, str) or not MAP_ID.fullmatch(map_id) or len(map_id) > 48:
            raise ValueError(f'Map {index + 1} has an invalid ID')
        if map_id in ids:
            raise ValueError(f'Duplicate map ID: {map_id}')
        ids.add(map_id)
        if type(entry.get('includeInGame')) is not bool:
            raise ValueError(f'Map {map_id} needs an includeInGame flag')
        recipe = entry.get('recipe')
        if not isinstance(recipe, dict):
            raise ValueError(f'Map {map_id} needs a recipe')
        name = recipe.get('name')
        if not isinstance(name, str) or not 1 <= len(name) <= 24 or not MAP_NAME.fullmatch(name):
            raise ValueError(f'Map {map_id} name must use 1-24 title-safe characters')
        if recipe.get('version') not in (1, 2, 3, 4, 5, 6, 7):
            raise ValueError(f'Map {map_id} has an unsupported recipe version')
        integer(recipe.get('seed'), 0, 0xffffffff, f'Map {map_id} seed')
        try:
            spawn_profiles(recipe)
            map_portals, map_player_spawns = placements(recipe, map_id)
        except ValueError as error:
            raise ValueError(f'Map {map_id}: {error}') from error
        try:
            validate_profile(recipe.get('artProfile'), art_catalog)
        except ValueError as error:
            raise ValueError(f'Map {map_id}: {error}') from error
        try:
            shop_profile = normalize_shop_profile(recipe.get('shopProfile'))
        except ValueError as error:
            raise ValueError(f'Map {map_id}: {error}') from error
        nodes = recipe.get('nodes')
        if not isinstance(nodes, list) or len(nodes) > MAX_NODES:
            raise ValueError(f'Map {map_id} must contain at most {MAX_NODES} nodes')
        if entry['includeInGame']:
            if not nodes:
                raise ValueError(f'Map {map_id} is enabled but its graph is empty')
            if not map_portals:
                raise ValueError(f'Map {map_id} is enabled but has no portals')
            if not map_player_spawns:
                raise ValueError(f'Map {map_id} is enabled but has no player spawns')
            try:
                for town in range(TOWN_COUNT):
                    resolve_inventory(shop_catalog, map_id, recipe['seed'], town, shop_profile)
            except ValueError as error:
                raise ValueError(f'Map {map_id}: {error}') from error
            if compile_maps:
                candidate = copy.deepcopy(recipe)
                compile_recipe(candidate)
                for key in ('materialOutput', 'spawnOutput', 'decorationOutput'):
                    if candidate.get(key) is not None:
                        compile_recipe(candidate, candidate[key])
            enabled.append(entry)
    if not enabled:
        raise ValueError('Enable at least one valid map for the game')
    enabled_ids = {entry['id'] for entry in enabled}
    portals, player_spawns = {}, {}
    for entry in enabled:
        map_portals, map_spawns = placements(entry['recipe'], entry['id'])
        portals[entry['id']] = {item['id']: item for item in map_portals}
        player_spawns[entry['id']] = {item['id']: item for item in map_spawns}
    reconcile_world(library, enabled, portals, player_spawns)
    world = library.get('world')
    if not isinstance(world, dict) or world.get('version') != 2:
        raise ValueError('The map library needs a version 2 world graph')
    start = world.get('start')
    if not isinstance(start, dict) or start.get('map') not in enabled_ids or \
       start.get('spawn') not in player_spawns[start.get('map')]:
        raise ValueError('The world start must reference an enabled map and player spawn')
    positions = world.get('nodes')
    if not isinstance(positions,list):
        raise ValueError('World graph nodes must be a list')
    positioned = set()
    for node in positions:
        if not isinstance(node,dict) or node.get('map') not in enabled_ids or node['map'] in positioned:
            raise ValueError('World graph map nodes must uniquely reference enabled maps')
        integer(node.get('x'),0,10000,'World graph X')
        integer(node.get('y'),0,10000,'World graph Y')
        positioned.add(node['map'])
    if positioned != enabled_ids:
        raise ValueError('Every enabled map needs one world graph node')
    links = world.get('connections')
    if not isinstance(links,list) or len(links)>256:
        raise ValueError('World graph connections must be a bounded list')
    used = set()
    for link in links:
        if not isinstance(link,dict):
            raise ValueError('World transitions must be objects')
        source,destination=link.get('from'),link.get('to')
        if not isinstance(source,dict) or source.get('map') not in enabled_ids or \
           source.get('portal') not in portals[source.get('map')]:
            raise ValueError('World transition references a missing source portal')
        if not isinstance(destination,dict) or destination.get('map') not in enabled_ids or \
           destination.get('spawn') not in player_spawns[destination.get('map')]:
            raise ValueError('World transition references a missing destination player spawn')
        key=(source['map'],source['portal'])
        if key in used:
            raise ValueError(f'World portal {key[0]}.{key[1]} has more than one destination')
        used.add(key)
    return enabled


def library_revision(data):
    return hashlib.sha256(data).hexdigest()


def load_library(path=LIBRARY_PATH, compile_maps=True):
    data = path.read_bytes()
    library = json.loads(data)
    enabled = validate_library(library, compile_maps)
    return library, enabled, library_revision(data)


def _program(text, symbol, program, fallback_op):
    rows = program or [[OPS[fallback_op][0], -1, -1, -1, 0, *([0] * PARAM_WORDS)]]
    text += f'inline constexpr mapgen::node {symbol}[]={{\n'
    for node in rows:
        text += '    {mapgen::op('+str(node[0])+'),'+','.join(map(str, node[1:5]))+'u,{'+','.join(map(str, node[5:]))+'}},\n'
    return text + '};\n'


def generate():
    library, entries, revision = load_library()
    art_catalog = load_art_catalog()
    shop_catalog = load_shop_catalog(map_ids={entry['id'] for entry in library['maps']})
    _, bank_indices, bank_keys = profiles_for_entries(entries, art_catalog)
    map_indices = {entry['id']: index for index,entry in enumerate(entries)}
    portal_lists = [entry['recipe']['portals'] for entry in entries]
    player_spawn_lists = [entry['recipe']['playerSpawns'] for entry in entries]
    portal_indices = [{item['id']: index for index,item in enumerate(items)} for items in portal_lists]
    player_spawn_indices = [{item['id']: index for index,item in enumerate(items)} for items in player_spawn_lists]
    transitions = [[(-1,-1) for _ in items] for items in portal_lists]
    for link in library['world']['connections']:
        source,destination=link['from'],link['to']
        source_map,destination_map=map_indices[source['map']],map_indices[destination['map']]
        portal=portal_indices[source_map][source['portal']]
        spawn=player_spawn_indices[destination_map][destination['spawn']]
        transitions[source_map][portal]=(destination_map,spawn)
    adjacency=[[] for _ in entries]
    for source,rows in enumerate(transitions):
        for portal,(destination,_) in enumerate(rows):
            if destination>=0:adjacency[source].append((destination,portal))
    next_portal=[[-1]*len(entries) for _ in entries]
    route_distance=[[255]*len(entries) for _ in entries]
    for source in range(len(entries)):
        route_distance[source][source]=0;queue=[source]
        while queue:
            at=queue.pop(0)
            for destination,portal in adjacency[at]:
                if route_distance[source][destination]!=255:continue
                route_distance[source][destination]=route_distance[source][at]+1
                next_portal[source][destination]=portal if at==source else next_portal[source][at]
                queue.append(destination)
    text = '// Generated from maps/map-library.json ('+revision[:12]+'). Do not edit.\n#pragma once\n#include "map_recipe.h"\n#include "spawn_profiles.h"\n'
    text += 'namespace map_catalog {\nstruct portal {\n    const char* id; uint16_t x,y,width,height; int8_t destination_map,destination_spawn;\n};\n'
    text += 'struct player_spawn { const char* id; uint16_t x,y; int16_t heading; };\n'
    text += 'struct shop_inventory { uint8_t count; uint8_t save_ids[9]; };\n'
    text += 'struct entry {\n    const char* id; const char* name; uint32_t seed; int art_bank;\n'
    text += '    const mapgen::node* nodes; int count;\n    const mapgen::node* material_nodes; int material_count;\n'
    text += '    const mapgen::node* spawn_nodes; int spawn_count;\n    const mapgen::node* decoration_nodes; int decoration_count;\n'
    text += '    const spawn_profiles::profile* spawn_profiles; int spawn_profile_count;\n'
    text += '    const portal* portals; int portal_count; const player_spawn* player_spawns; int player_spawn_count;\n'
    text += '    const shop_inventory* shops;\n};\n'
    compiled = []
    for index, entry in enumerate(entries):
        recipe = copy.deepcopy(entry['recipe'])
        branches = {
            'nodes': compile_recipe(recipe),
            'material_nodes': compile_recipe(recipe, recipe['materialOutput']) if recipe.get('materialOutput') is not None else [],
            'spawn_nodes': compile_recipe(recipe, recipe['spawnOutput']) if recipe.get('spawnOutput') is not None else [],
            'decoration_nodes': compile_recipe(recipe, recipe['decorationOutput']) if recipe.get('decorationOutput') is not None else [],
        }
        for name, program in branches.items():
            fallback = 'materials' if name == 'material_nodes' else 'spawns' if name == 'spawn_nodes' else 'decoration' if name == 'decoration_nodes' else 'world'
            text = _program(text, f'map_{index}_{name}', program, fallback)
        profiles = spawn_profiles(recipe)
        text += f'inline constexpr spawn_profiles::profile map_{index}_spawn_profiles[]={{\n'
        for profile in profiles:
            frames = profile['respawnSeconds'] * 60
            text += ('    {'+str(profile['id'])+',spawn_profiles::enemy::'+profile['enemy']+','+str(frames)+','+
                     str(profile['scrapChance'])+','+str(profile['scrapMin'])+','+str(profile['scrapMax'])+
                     ','+str(profile['energyChance'])+','+str(profile['energyMin'])+','+
                     str(profile['energyMax'])+'},\n')
        text += '};\n'
        text += f'inline constexpr portal map_{index}_portals[]={{\n'
        for portal_index,item in enumerate(portal_lists[index]):
            destination,destination_spawn=transitions[index][portal_index]
            values=(item['x'],item['y'],item['width'],item['height'],destination,destination_spawn)
            text += '    {'+json.dumps(item['id'])+','+','.join(map(str,values))+'},\n'
        text += '};\n'
        text += f'inline constexpr player_spawn map_{index}_player_spawns[]={{\n'
        for item in player_spawn_lists[index]:
            text += '    {'+json.dumps(item['id'])+','+','.join(map(str,(item['x'],item['y'],item['heading'])))+'},\n'
        text += '};\n'
        shops = [resolve_inventory(shop_catalog, entry['id'], recipe['seed'], town,
                                   recipe.get('shopProfile')) for town in range(TOWN_COUNT)]
        text += f'inline constexpr shop_inventory map_{index}_shops[]={{\n'
        for shop in shops:
            padded = shop['saveIds'] + [0] * (9 - len(shop['saveIds']))
            text += '    {' + str(len(shop['saveIds'])) + ',{' + ','.join(map(str, padded)) + '}},\n'
        text += '};\n'
        compiled.append((entry, recipe, branches))
    text += 'inline constexpr entry maps[]={\n'
    for index, (entry, recipe, branches) in enumerate(compiled):
        fields = []
        for name in ('nodes', 'material_nodes', 'spawn_nodes', 'decoration_nodes'):
            fields.extend((f'map_{index}_{name}', str(len(branches[name]))))
        fields.extend((f'map_{index}_spawn_profiles',str(len(spawn_profiles(recipe)))))
        fields.extend((f'map_{index}_portals',str(len(portal_lists[index]))))
        fields.extend((f'map_{index}_player_spawns',str(len(player_spawn_lists[index]))))
        fields.append(f'map_{index}_shops')
        text += '    {'+json.dumps(entry['id'])+','+json.dumps(recipe['name'].upper())+','+str(recipe['seed'])+'u,'+str(bank_indices[bank_keys[index]])+','+','.join(fields)+'},\n'
    text += '};\ninline constexpr int count=sizeof(maps)/sizeof(maps[0]);\n'
    start=library['world']['start'];start_map=map_indices[start['map']]
    text += 'inline constexpr int start_map='+str(start_map)+';\n'
    text += 'inline constexpr int start_spawn='+str(player_spawn_indices[start_map][start['spawn']])+';\n'
    text += 'inline constexpr int8_t next_portal[count*count]={'+','.join(str(value) for row in next_portal for value in row)+'};\n'
    text += 'inline constexpr uint8_t route_distance[count*count]={'+','.join(str(value) for row in route_distance for value in row)+'};\n}\n'
    output = ROOT / 'include/generated/wasteland_recipe.h'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    snapshot=ROOT/'artifacts/wasteland/active-map-library.json'
    snapshot.parent.mkdir(parents=True,exist_ok=True)
    snapshot.write_text(json.dumps(library,indent=2)+'\n')
    print(f'Map library: {len(entries)} game maps / {len(library["maps"])-len(entries)} drafts')


if __name__ == '__main__':
    generate()
