// Cross-runtime byte parity using fixtures generated by the native C++ bridge.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {compile,makeNode,presets} from './map_editor/recipe.mjs';
const root=new URL('../',import.meta.url),out=new URL('build/map-recipe-tests/',root);
const schema=JSON.parse(await readFile(new URL('tools/map_editor/schema.json',root),'utf8'));
const original=JSON.parse(await readFile(new URL('maps/recipes/wasteland.json',root),'utf8'));
const legacy={version:1,name:'Legacy fixture',seed:12648430,output:3,nodes:[
  {...makeNode(schema,'random',1),stream:0},
  {...makeNode(schema,'cellular',2),inputs:{a:1}},
  {...makeNode(schema,'world',3),inputs:{a:2}}
]};
const examples=presets(schema,legacy);
if(process.argv.includes('--prepare')) {
  await mkdir(out,{recursive:true});
  const fixtures=[];
  function add(recipe,seed,target=recipe.output,tag=recipe.name) {
    const compiled=compile(recipe,schema,target);
    fixtures.push({program:compiled.program,seed,tag,recipe:structuredClone(recipe),target});
  }
  for(let i=0;i<128;++i)add(legacy,i===0?12648430:Math.imul(i,2654435761)>>>0,3,'legacy');
  for(const example of examples)for(const seed of [0,1,42,12648430,0xffffffff])
    for(const node of example.nodes)add(example,seed,node.id);
  for(const density of [0,47,100])for(const neighbours of [4,8]) {
    const recipe=structuredClone(legacy);recipe.nodes[0].p=[density,0];
    recipe.nodes[1].p=[3,2,16,0,neighbours];recipe.nodes[1].inputs.mask=1;
    add(recipe,0xffffffff,2,`masked-ca-${density}-${neighbours}`);
    recipe.nodes[1].p[0]=0;add(recipe,0,2,'zero-iterations');
  }
  const blend={version:1,seed:42,output:4,name:'Masked blend',nodes:[
    makeNode(schema,'radial',1),makeNode(schema,'plasma',2),makeNode(schema,'random',3),
    {...makeNode(schema,'blend',4),inputs:{a:1,b:2,mask:3}}
  ]};add(blend,42);
  for(let mode=0;mode<4;++mode){const r=structuredClone(legacy);r.nodes.push({...makeNode(schema,'invert',4),inputs:{a:1}},
    {...makeNode(schema,'combine',5),inputs:{a:1,b:4},p:[mode]});add(r,42,5,`combine-${mode}`);}
  add(original,original.seed,original.output,'active');
  for(const id of [0,3,127,255]){
    const r=structuredClone(legacy);r.version=2;r.materialOutput=6;
    r.nodes.push({...makeNode(schema,'field_fill',4),p:[id]},
      {...makeNode(schema,'field_paint',5),inputs:{a:4,mask:1},p:[255-id]},
      {...makeNode(schema,'materials',6),inputs:{a:5}});
    add(r,42,6,`material-paint-${id}`);
  }
  const patches=structuredClone(legacy);patches.nodes.push(makeNode(schema,'material_patches',4));
  for(const seed of [0,42,12648430,0xffffffff])add(patches,seed,4,'original-ground-patches');
  const dense=structuredClone(examples[4]),denseLut=dense.nodes.find(n=>n.type==='field_lut');denseLut.p=[255,0,...Array.from({length:255},(_,i)=>[i+1,(i+1)&255]).flat()];delete denseLut.colors;
  add(dense,42,denseLut.id,'dense-lut-255-points');
  await writeFile(new URL('manifest.json',out),JSON.stringify(fixtures));
  for(let i=0;i<fixtures.length;++i)await writeFile(new URL(`${i}.program`,out),new Uint32Array(fixtures[i].program.flat()));
  const bad=structuredClone(legacy);bad.nodes[1].inputs.a=2;assert.throws(()=>compile(bad,schema),/cycle/);
  bad.nodes[1].inputs.a=3;assert.throws(()=>compile(bad,schema),/cycle/);
  bad.nodes[1].inputs.a=999;assert.throws(()=>compile(bad,schema),/Connect/);
  bad.nodes[1].inputs.a=1;bad.nodes[1].p[0]=33;assert.throws(()=>compile(bad,schema),/Iterations/);
  bad.nodes[1].p[0]=5;bad.nodes[0].type='radial';bad.nodes[0].p=[32,32,30,0];assert.throws(()=>compile(bad,schema),/needs mask/);
  bad.version=99;assert.throws(()=>compile(bad,schema),/Unsupported/);
  const reordered=structuredClone(legacy);reordered.nodes.reverse();assert.deepEqual(compile(reordered,schema).program,compile(legacy,schema).program);
  reordered.nodes.push(makeNode(schema,'random',4));assert.deepEqual(compile(reordered,schema).program,compile(legacy,schema).program);
  const longRecipe={version:1,name:'64 node chain',seed:42,output:64,nodes:[makeNode(schema,'random',1)]};
  for(let id=2;id<=64;++id)longRecipe.nodes.push({...makeNode(schema,'invert',id),inputs:{a:id-1}});
  assert.equal(compile(longRecipe,schema).program.length,64);
  longRecipe.nodes.push({...makeNode(schema,'invert',65),inputs:{a:64}});
  assert.throws(()=>compile(longRecipe,schema),/64 nodes/);
  const materialBad=structuredClone(examples[4]),badLut=materialBad.nodes.find(n=>n.type==='field_lut');badLut.p[4]=badLut.p[2];
  assert.throws(()=>compile(materialBad,schema),/unique/);
  delete materialBad.materialOutput;assert.throws(()=>compile(materialBad,schema),/unique|Ground/);
  const crossed=structuredClone(examples[4]),crossedLut=crossed.nodes.find(n=>n.type==='field_lut');crossedLut.p=[3,9,200,1,50,2,120,3];
  const crossedWords=compile(crossed,schema,crossedLut.id).program.at(-1).slice(5),lutByte=(words,value)=>(words[value>>2]>>>((value&3)*8))&255;
  assert.equal(crossedWords.length,64);assert.deepEqual([0,49,50,119,120,199,200,255].map(v=>lutByte(crossedWords,v)),[9,9,2,2,3,3,1,1]);
  const denseWords=compile(dense,schema,denseLut.id).program.at(-1).slice(5);assert.equal(denseWords.length,64);for(let value=0;value<256;++value)assert.equal(lutByte(denseWords,value),value);
  const retired=structuredClone(examples[4]),retiredLut=retired.nodes.find(n=>n.type==='field_lut');retiredLut.type='material_bands';retiredLut.p=[64,128,192,4,5,6,7];
  compile(retired,schema,retiredLut.id);assert.equal(retiredLut.type,'field_lut');assert.deepEqual(retiredLut.p,[3,4,64,5,128,6,192,7]);
  const renderCases=[{name:'original',recipe:legacy,seed:12648430},{name:'natural',recipe:examples[4],seed:12648430},
    {name:'natural-zero',recipe:examples[4],seed:0}];
  const reserved=structuredClone(legacy);reserved.version=2;reserved.materialOutput=5;
  reserved.nodes.push({...makeNode(schema,'field_fill',4),p:[255]},{...makeNode(schema,'materials',5),inputs:{a:4}});
  renderCases.push({name:'roads',recipe:examples[5],seed:12648430});
  const wide=structuredClone(examples[5]);wide.nodes.at(-1).p=[256,1];
  renderCases.push({name:'roads-wide',recipe:wide,seed:42});
  renderCases.push({name:'reserved-id',recipe:reserved,seed:42});
  const library=JSON.parse(await readFile(new URL('maps/map-library.json',root),'utf8'));
  const active=library.maps.find(entry=>entry.includeInGame).recipe;
  renderCases.push({name:'active',recipe:active,seed:active.seed});
  const legacyRoads=structuredClone(examples[5]);legacyRoads.nodes.at(-1).p=[153,3,170];
  const migrated=compile(legacyRoads,schema);assert.deepEqual(migrated.program.at(-1).slice(5,8),[160,3,0]);
  for(const f of renderCases){f.world=compile(f.recipe,schema).program;f.materials=f.recipe.materialOutput==null?[]:compile(f.recipe,schema,f.recipe.materialOutput).program;
    await writeFile(new URL(`${f.name}.world`,out),new Uint32Array(f.world.flat()));
    if(f.materials.length)await writeFile(new URL(`${f.name}.materials`,out),new Uint32Array(f.materials.flat()));}
  await writeFile(new URL('render-manifest.json',out),JSON.stringify(renderCases));
  console.log(`Prepared ${fixtures.length} native/WASM cases; graph validation and stable ordering passed.`);
} else {
  const createEngine=(await import('./map_editor/generated/engine.mjs')).default;
  const engine=await createEngine();
  const fixtures=JSON.parse(await readFile(new URL('manifest.json',out),'utf8'));
  for(let i=0;i<fixtures.length;++i){
    const f=fixtures[i];engine.HEAPU32.set(new Uint32Array(f.program.flat()),engine._recipe_input()>>>2);
    assert.equal(engine._recipe_run(f.program.length,f.seed),0,`execution ${i}: ${f.tag}`);
    const actual=Buffer.concat([
      Buffer.from(engine.HEAPU8.slice(engine._recipe_meta(),engine._recipe_meta()+80)),
      Buffer.from(engine.HEAPU8.slice(engine._recipe_cells(),engine._recipe_cells()+4096))
    ]);
    const expected=await readFile(new URL(`${i}.result`,out));assert.deepEqual(actual,expected,`native/WASM ${i}: ${f.tag}`);
  }
  const library=JSON.parse(await readFile(new URL('maps/map-library.json',root),'utf8')),active=library.maps.find(entry=>entry.id==='wasteland').recipe,program=compile(active,schema).program;
  engine.HEAPU32.set(new Uint32Array(program.flat()),engine._recipe_input()>>>2);assert.equal(engine._recipe_run(program.length,active.seed),0);assert.equal(engine._recipe_apply_exits(15),0);
  const cells=engine.HEAPU8.slice(engine._recipe_cells(),engine._recipe_cells()+4096);assert.equal(cells[31],0);assert.equal(cells[31*64+63],0);assert.equal(cells[63*64+31],0);assert.equal(cells[31*64],0);
  const reserved=engine._recipe_reserved();assert.ok(engine.HEAPU8.slice(reserved,reserved+1024*1024).some(Boolean));
  const report={cases:fixtures.length,legacySeeds:128,nativeWasmByteParity:true,graphValidation:true,wasmSha256:(await import('node:crypto')).createHash('sha256').update(await readFile(new URL('tools/map_editor/generated/engine.wasm',root))).digest('hex')};
  await mkdir(new URL('artifacts/map_editor/',root),{recursive:true});
  await writeFile(new URL('artifacts/map_editor/parity-results.json',root),JSON.stringify(report,null,2)+'\n');
  console.log(`PASS ${fixtures.length} native / WebAssembly byte comparisons, including metadata, maps, spawn and outposts.`);
}
